Implement the command that allows users to view other user's timezone
bijij/BotBot pull request #3
Opened 2021-04-15 19:48 UTC by fwrs

Hello again, Josh B. Ijiji.

In this pull request I would like to fix this issue with your Bot (stylized as BotBot) where it doesn't have a command that allows us, the users of your Bot (stylized as BotBot) to view the timezones of your Bot's (stylized as BotBot) members (the formal audience that interacts with your bot). This is a task of great scale that I formally requested you to implement exactly 5 seconds ago, however it occurred to me that I could fix it myself, and so I did. Please take great care while reviewing this tremendously massive GitHub Pull Request, there's a great amount of new logic added, that requires immaculate internal Quality Assurance processes and masterful code review.

This pull request fixes #2.

Best regards, Ilya C. Onecat.

2021-04-15 19:49 UTC, Zomatree approved these changes

2021-04-15 19:49 UTC, NCPlayz approved these changes

2021-04-15 19:50 UTC, AbstractUmbra approved these changes
Looks good.

2021-04-16 06:13 UTC, bijij requested changes
Good PR, just need a couple fix-ups, and QoL improvements.

2021-04-16 06:13 UTC, bijij commented on cogs/logging/logging.py
> +            return await ctx.send(embed = embed)
Use built-in error handler.

```suggestion
        if timezone is None:
           raise commands.BadArgument(f"User {user.name} doesn't have a saved timezone.")
```

2021-04-16 06:13 UTC, bijij commented on cogs/logging/logging.py
> +        timezone = await Timezones.fetchrow(user_id=user.id)
Only display time-zones for opted in users.

```suggestion
        async with ctx.db as conn:
            await Opt_In_Status.is_public(ctx, user, connection=conn)
            timezone = await Timezones.fetchrow(connection=conn, user_id=user.id)
```

2021-04-16 06:13 UTC, bijij commented on cogs/logging/logging.py
> +        """Get a member's timezone."""
Default to ctx.author if no user is passed.

```suggestion
    async def timezone_get(self, ctx, *, user: discord.User = None):
        """Get a user's timezone.
        
        `user`: The user who's timezone to display, defaults to you.
        """
        user = user or ctx.author
```

2021-04-16 06:13 UTC, bijij commented on cogs/logging/logging.py
> +        await ctx.send(embed = embed)
Display UTC offset

```suggestion
        tzinfo = zoneinfo.ZoneInfo(timezone['timezone'])
        delta = tzinfo.utcoffset(discord.utils.utcnow())
        seconds = int(delta.total_seconds())
        
        utc_offset = f"UTC{'+' if seconds >= 0 else '-'}{abs(seconds) // 3600:02}:{abs(seconds) // 60 % 60:02}"

        await ctx.send(embed=discord.Embed(
            title="Timezone info",
            description=f"User {user.name}'s timezone is {tzinfo} ({utc_offset})",
            colour=discord.Colour.blue()
        ))
        
```

2021-04-16 08:01 UTC, fwrs commented
Thank you Josh B. Ijiji for the wonderful and thorough code review. I have put in the effort to fix all the issues that you've presented me with.

Best regards, Ilya C. Onecat.

2021-04-16 08:01 UTC, AbstractUmbra approved these changes
Changes are clean!
おめでとう！

2021-04-16 08:01 UTC, bijij approved these changes

2021-04-16 08:01 UTC, merged

2021-04-16 11:29 UTC, NCPlayz commented
Thank you for merging this excellent feature! 😄